// This file declares the blog module's PUBLIC API: the contract other
// modules use to talk to it. Consumers depend on this interface and the public
// DTOs defined alongside it (see the per-model *_api.go files), never on the
// module's internal/ packages.
//
// This file is regenerated by `brrr generate`.
package blog

import (
	"context"

	"github.com/google/uuid"
)

// API is the blog module's public contract for other modules. A consuming
// module declares a dependency on this interface and receives the blog
// Module at wiring time in internal/modules/registry.go.
type API interface {
	PostByID(ctx context.Context, id uuid.UUID) (Post, error)
	CommentByID(ctx context.Context, id uuid.UUID) (Comment, error)
}

// Compile-time guarantee that the module satisfies its own public API.
var _ API = (*Module)(nil)
