// Package blog assembles the blog module from its model slices
// and exposes it as a mountable Module. It also implements the module's public
// API (see api.go), the contract other modules use to reach it.
//
// This file is regenerated by `brrr generate`; edit the per-model files instead.
package blog

import (
	"github.com/go-chi/chi/v5"
	"github.com/go-playground/validator/v10"

	"github.com/example/blog/internal/db"
	bloghttp "github.com/example/blog/internal/modules/blog/internal/adapters/http"
	"github.com/example/blog/internal/modules/blog/internal/adapters/postgres"
	"github.com/example/blog/internal/modules/blog/internal/services"
	"github.com/example/blog/internal/platform/auth"
)

// Deps are the blog module's construction dependencies.
type Deps struct {
	Queries   *db.Queries
	Tokens    *auth.TokenService
	Validator *validator.Validate
}

// Module is the blog feature module. It owns each model's service, which
// backs both the HTTP transport and the module's public API.
type Module struct {
	tokens   *auth.TokenService
	validate *validator.Validate
	postSvc *services.PostService
	commentSvc *services.CommentService
}

// New wires the module's models together.
func New(d Deps) *Module {
	return &Module{
		tokens:   d.Tokens,
		validate: d.Validator,
		postSvc: services.NewPostService(postgres.NewPostRepository(d.Queries)),
		commentSvc: services.NewCommentService(postgres.NewCommentRepository(d.Queries)),
	}
}

// Name identifies the module.
func (m *Module) Name() string { return "blog" }

// RegisterRoutes mounts every model's routes.
func (m *Module) RegisterRoutes(r chi.Router) {
	bloghttp.NewPostHandler(m.postSvc, m.validate).RegisterRoutes(r, m.tokens)
	bloghttp.NewCommentHandler(m.commentSvc, m.validate).RegisterRoutes(r, m.tokens)
}
