// This file declares the sales module's PUBLIC API: the contract other
// modules use to talk to it. Consumers depend on this interface and the public
// DTOs defined alongside it (see the per-model *_api.go files), never on the
// module's internal/ packages.
//
// This file is regenerated by `brrr generate`.
package sales

import (
	"context"

	"github.com/google/uuid"
)

// API is the sales module's public contract for other modules. A consuming
// module declares a dependency on this interface and receives the sales
// Module at wiring time in internal/modules/registry.go.
type API interface {
	OrderByID(ctx context.Context, id uuid.UUID) (Order, error)
	OrderItemByID(ctx context.Context, id uuid.UUID) (OrderItem, error)
}

// Compile-time guarantee that the module satisfies its own public API.
var _ API = (*Module)(nil)
