// Package sales assembles the sales module from its model slices
// and exposes it as a mountable Module. It also implements the module's public
// API (see api.go), the contract other modules use to reach it.
//
// This file is regenerated by `brrr generate`; edit the per-model files instead.
package sales

import (
	"github.com/go-chi/chi/v5"
	"github.com/go-playground/validator/v10"

	"github.com/example/shop/internal/db"
	saleshttp "github.com/example/shop/internal/modules/sales/internal/adapters/http"
	"github.com/example/shop/internal/modules/sales/internal/adapters/postgres"
	"github.com/example/shop/internal/modules/sales/internal/services"
	"github.com/example/shop/internal/platform/auth"
)

// Deps are the sales module's construction dependencies.
type Deps struct {
	Queries   *db.Queries
	Tokens    *auth.TokenService
	Validator *validator.Validate
}

// Module is the sales feature module. It owns each model's service, which
// backs both the HTTP transport and the module's public API.
type Module struct {
	tokens   *auth.TokenService
	validate *validator.Validate
	orderSvc *services.OrderService
	orderItemSvc *services.OrderItemService
}

// New wires the module's models together.
func New(d Deps) *Module {
	return &Module{
		tokens:   d.Tokens,
		validate: d.Validator,
		orderSvc: services.NewOrderService(postgres.NewOrderRepository(d.Queries)),
		orderItemSvc: services.NewOrderItemService(postgres.NewOrderItemRepository(d.Queries)),
	}
}

// Name identifies the module.
func (m *Module) Name() string { return "sales" }

// RegisterRoutes mounts every model's routes.
func (m *Module) RegisterRoutes(r chi.Router) {
	saleshttp.NewOrderHandler(m.orderSvc, m.validate).RegisterRoutes(r, m.tokens)
	saleshttp.NewOrderItemHandler(m.orderItemSvc, m.validate).RegisterRoutes(r, m.tokens)
}
