// Package catalog assembles the catalog module from its model slices
// and exposes it as a mountable Module. It also implements the module's public
// API (see api.go), the contract other modules use to reach it.
//
// This file is regenerated by `brrr generate`; edit the per-model files instead.
package catalog

import (
	"github.com/go-chi/chi/v5"
	"github.com/go-playground/validator/v10"

	"github.com/example/shop/internal/db"
	cataloghttp "github.com/example/shop/internal/modules/catalog/internal/adapters/http"
	"github.com/example/shop/internal/modules/catalog/internal/adapters/postgres"
	"github.com/example/shop/internal/modules/catalog/internal/services"
	"github.com/example/shop/internal/platform/auth"
)

// Deps are the catalog module's construction dependencies.
type Deps struct {
	Queries   *db.Queries
	Tokens    *auth.TokenService
	Validator *validator.Validate
}

// Module is the catalog feature module. It owns each model's service, which
// backs both the HTTP transport and the module's public API.
type Module struct {
	tokens   *auth.TokenService
	validate *validator.Validate
	categorySvc *services.CategoryService
	productSvc *services.ProductService
}

// New wires the module's models together.
func New(d Deps) *Module {
	return &Module{
		tokens:   d.Tokens,
		validate: d.Validator,
		categorySvc: services.NewCategoryService(postgres.NewCategoryRepository(d.Queries)),
		productSvc: services.NewProductService(postgres.NewProductRepository(d.Queries)),
	}
}

// Name identifies the module.
func (m *Module) Name() string { return "catalog" }

// RegisterRoutes mounts every model's routes.
func (m *Module) RegisterRoutes(r chi.Router) {
	cataloghttp.NewCategoryHandler(m.categorySvc, m.validate).RegisterRoutes(r, m.tokens)
	cataloghttp.NewProductHandler(m.productSvc, m.validate).RegisterRoutes(r, m.tokens)
}
