// Package projects assembles the projects module from its model slices
// and exposes it as a mountable Module. It also implements the module's public
// API (see api.go), the contract other modules use to reach it.
//
// This file is regenerated by `brrr generate`; edit the per-model files instead.
package projects

import (
	"github.com/go-chi/chi/v5"
	"github.com/go-playground/validator/v10"

	"github.com/example/tasks/internal/db"
	projectshttp "github.com/example/tasks/internal/modules/projects/internal/adapters/http"
	"github.com/example/tasks/internal/modules/projects/internal/adapters/postgres"
	"github.com/example/tasks/internal/modules/projects/internal/services"
	"github.com/example/tasks/internal/platform/auth"
)

// Deps are the projects module's construction dependencies.
type Deps struct {
	Queries   *db.Queries
	Tokens    *auth.TokenService
	Validator *validator.Validate
}

// Module is the projects feature module. It owns each model's service, which
// backs both the HTTP transport and the module's public API.
type Module struct {
	tokens   *auth.TokenService
	validate *validator.Validate
	projectSvc *services.ProjectService
	taskSvc *services.TaskService
	labelSvc *services.LabelService
}

// New wires the module's models together.
func New(d Deps) *Module {
	return &Module{
		tokens:   d.Tokens,
		validate: d.Validator,
		projectSvc: services.NewProjectService(postgres.NewProjectRepository(d.Queries)),
		taskSvc: services.NewTaskService(postgres.NewTaskRepository(d.Queries)),
		labelSvc: services.NewLabelService(postgres.NewLabelRepository(d.Queries)),
	}
}

// Name identifies the module.
func (m *Module) Name() string { return "projects" }

// RegisterRoutes mounts every model's routes.
func (m *Module) RegisterRoutes(r chi.Router) {
	projectshttp.NewProjectHandler(m.projectSvc, m.validate).RegisterRoutes(r, m.tokens)
	projectshttp.NewTaskHandler(m.taskSvc, m.validate).RegisterRoutes(r, m.tokens)
	projectshttp.NewLabelHandler(m.labelSvc, m.validate).RegisterRoutes(r, m.tokens)
}
